#!/bin/fish
# Copyright 2019 Alexander Wilhelmi
# This file is part of mailcheck.
# 
# mailcheck is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# mailcheck is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with mailcheck.  If not, see <http://www.gnu.org/licenses/>.
# 
# Diese Datei ist Teil von mailcheck.
# 
# mailcheck ist Freie Software: Sie können es unter den Bedingungen
# der GNU General Public License, wie von der Free Software Foundation,
# Version 3 der Lizenz oder (nach Ihrer Wahl) jeder neueren
# veröffentlichten Version, weiter verteilen und/oder modifizieren.
# 
# mailcheck wird in der Hoffnung, dass es nützlich sein wird, aber
# OHNE JEDE GEWÄHRLEISTUNG, bereitgestellt; sogar ohne die implizite
# Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
# Siehe die GNU General Public License für weitere Details.
# 
# Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
# Programm erhalten haben. Wenn nicht, siehe <https://www.gnu.org/licenses/>.
while true
  begin
     begin
	      echo -n "notmuch mailcheck: "
		  notmuch new
     end |logger -p mail.info
  end 2>&1 |logger -p mail.error
  find -L $HOME"/.my_notmuchfs/unread" -type f|wc -l > ~/.recent_unread_mailcount 2>| logger -p mail.error
  sleep 20
end
